// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLSfS4yvywOLZlKfplQCx7rHmehve6GlI',
    appId: '1:744515142102:web:2be80de5c4f1b80ce0a477',
    messagingSenderId: '744515142102',
    projectId: 'uniflow-bf05e',
    authDomain: 'uniflow-bf05e.firebaseapp.com',
    storageBucket: 'uniflow-bf05e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHiDpsJSQjlovi6wCyM0bgXHnzMJxHfNs',
    appId: '1:744515142102:android:fec5f58a13fc9335e0a477',
    messagingSenderId: '744515142102',
    projectId: 'uniflow-bf05e',
    storageBucket: 'uniflow-bf05e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAxay7FJdxiAw7SWyW3lTy8n_m_mZJZWr4',
    appId: '1:744515142102:ios:1948cb135dc9a927e0a477',
    messagingSenderId: '744515142102',
    projectId: 'uniflow-bf05e',
    storageBucket: 'uniflow-bf05e.firebasestorage.app',
    iosBundleId: 'com.example.uniflow',
  );
}
