// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQTBhCd3E3PddI98VrRN2tWEMfF1Us4jc',
    appId: '1:256211254063:web:a2fcf60d370202992affda',
    messagingSenderId: '256211254063',
    projectId: 'uniflow2-63ee5',
    authDomain: 'uniflow2-63ee5.firebaseapp.com',
    storageBucket: 'uniflow2-63ee5.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAtUR_cAldreZGIj6Qaz90YwrpvDlaf-c',
    appId: '1:256211254063:android:4c442fab2739776b2affda',
    messagingSenderId: '256211254063',
    projectId: 'uniflow2-63ee5',
    storageBucket: 'uniflow2-63ee5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAVNw5PDpDi4nIL0vyidWIBWtzZ-kElnw8',
    appId: '1:256211254063:ios:ccf2e63039d665e42affda',
    messagingSenderId: '256211254063',
    projectId: 'uniflow2-63ee5',
    storageBucket: 'uniflow2-63ee5.firebasestorage.app',
    iosBundleId: 'com.example.uniflow',
  );
}
